version: "3.7"

services:

  api:
    build:
      context: ./api
    container_name: api
    volumes:
      - ./api/src:/src
    ports:
      - 5001:5000
    restart: always
    depends_on:
      - db

  realtimeml:
    build:
      context: ./realtimeml
    container_name: realtimeml
    volumes:
      - ./realtimeml/src:/src
    ports:
      - 5002:5000
    restart: always
    depends_on:
      - db

  db:
    build:
      context: ./db
    restart: always
    container_name: db
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: fNLM#D6544nrWGQ

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend/code/public:/code/public
      - ./frontend/code/src:/code/src
      - ./frontend/code/package.json:/code/package.json
      - ./frontend/code/package-lock.json:/code/package-lock.json
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - PUBLIC_URL=http://localhost:3000
    depends_on:
      - api