version: "3.7"

services:

  api:
    build:
      context: ./api
    container_name: api
    volumes:
      - ./api/src:/src
    ports:
      - 5001:5000
    restart: always
    depends_on:
      - db

  db:
    build:
      context: ./db
    restart: always
    container_name: db
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: fNLM#D6544nrWGQ